# Site settings
title: PerfAudit | Performance Audit of Websites and Web Applications by Professionals
email: info@perfaudit.com
description: > # this means to ignore newlines until "baseurl:"
  .
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://perfaudit.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
