# Site settings
title: PerfAudit | Performance Audit of Websites by Professionals
email: info@perfaudit.com
description: "Performance Audit of Websites by Professionals. Run Jank Free and Performant Web Applications care free."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://perfaudit.com" # the base hostname & protocol for your site
permalink: ":categories/:title"